"""init

Revision ID: f85fa9a38175
Revises: 
Create Date: 2023-09-27 16:12:40.053487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f85fa9a38175"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "phone_number",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("phone", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("phone_number_id", sa.Integer(), nullable=False),
        sa.Column("field1", sa.String(length=255), nullable=True),
        sa.Column("field2", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("middle_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("field5", sa.Integer(), nullable=True),
        sa.Column("field6", sa.String(length=255), nullable=True),
        sa.Column("field7", sa.String(length=255), nullable=True),
        sa.Column("birth_day", sa.DateTime(), nullable=True),
        sa.Column("field9", sa.Integer(), nullable=True),
        sa.Column("field10", sa.Integer(), nullable=True),
        sa.Column("field11", sa.String(length=255), nullable=True),
        sa.Column("field12", sa.String(length=255), nullable=True),
        sa.Column("field13", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["phone_number_id"],
            ["phone_number.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_data")
    op.drop_table("phone_number")
    # ### end Alembic commands ###
